### ISSUE TITLE
Crontab not running or howto autostart storj daemo 

### ISSUE THREAD

**Issue by jensamberg** [zannen/docker-storjshare-cli#10]
Hello thanks for the good job for the storj container

I tried to autostart the storj daemon. But i think the crond ist not running

Is there a way to execute a script at boot?

**Comment by zannen** [comment]
There is definitely a way to run a script at boot. Use an `init script` or a `systemd` script, depending on what your Linux distribution uses.

**Comment by jensamberg** [comment]
It is done thanks for help.
