### ISSUE TITLE
Exec format error on Raspbian

### ISSUE THREAD

**Issue by silveringking** [zannen/docker-storjshare-cli#13]
While trying to install storj img on my rapsberry pi 3 I got the following errors (I tried the two ways possible).

```
pi@raspberrypi:~/storj $ sudo docker build -t oreandawe/storjshare-cli:latest docker-storjshare-cli/
Sending build context to Docker daemon 109.6 kB
Step 0 : FROM gliderlabs/alpine:3.4
3.4: Pulling from gliderlabs/alpine
1d030f10025e: Pull complete 
10982af53a69: Already exists 
Digest: sha256:3b7126ad01f8e4dbd2eee78032414e8041a19251d2c11022b641e31a18d7095f
Status: Downloaded newer image for gliderlabs/alpine:3.4
 ---> 1d030f10025e
Step 1 : RUN apk add --no-cache bash g++ gcc git make nodejs python && 	export MAKEFLAGS=-j8 && 	npm install -g storjshare-daemon && 	git clone https://github.com/calxibe/StorjMonitor.git /opt/StorjMonitor && 	chmod +x /opt/StorjMonitor/storjMonitor.sh && 	rm -rf /opt/StorjMonitor/node_modules && 	npm --prefix /opt/StorjMonitor/ install && 	npm cache clear --force && 	apk del --no-cache g++ gcc git make python
 ---> Running in 11fa3bde7703
exec format error
[8] System error: exec format error
```

How can I fix this?

**Comment by zannen** [comment]
I'm not sure about the `exec format error`, I haven't seen that error before, but according to a Docker forum page [Docker error "exec format error"](https://forums.docker.com/t/docker-error-exec-format-error/4164), the error is due to a processor architecture mismatch, for example if the container was built for a 64-bit system, but you're using a 32-bit system.

**Comment by zannen** [comment]
I'll build a container on my PiZero and upload that (with a tag other than `latest` of course).

**Comment by zannen** [comment]
I found a list of [Alpine base images for various architectures](https://github.com/docker-library/repo-info/blob/master/repos/alpine/tag-details.md#alpine20190228---linux-arm-variant-v6). I'm using the image called "`alpine:20190228 - linux; arm variant v6`".

**Comment by zannen** [comment]
@silveringking I've created an `armv6l` image on my PiZero: https://hub.docker.com/r/oreandawe/storjshare-cli/tags

Give it a go...

**Comment by silveringking** [comment]
@zannen  there are still issue regarding the swap memory. I knew it was about the build per se yesterday but I was so tired I forgot to comment it.

`sudo docker run --detach --name mystorjdaemon --restart=always -v /media/pi/storj1:/storj1 -v /media/pi/storj2:/storj2 -v /media/pi/storj3:/storj3 -v /media/pi/storj4:/storj4 -p 4000-4003:4000-4003 -e WALLET_ADDRESS=[edited] -e DAEMONADDRESS=127.0.0.1 -e DATADIR=/storj -e SHARE_SIZE=4.5TB -e RPCADDRESS=0.0.0.0 -e RPCPORT=4000 -e TUNNELING_REQUIRED=TRUE -e STORJ_MONITOR_API_KEY=[edited] -e USE_HOSTNAME_SUFFIX=FALSE oreandawe/storjshare-cli:armv6l
Unable to find image 'oreandawe/storjshare-cli:armv6l' locally
armv6l: Pulling from oreandawe/storjshare-cli
309a8f4417bb: Pull complete 
05b1ad9d506a: Pull complete 
d6e2d725b39d: Pull complete 
57f9f131e2a3: Pull complete 
c44f1c7e2eed: Pull complete 
1d65ff8b0ec2: Pull complete 
9c756ccd8c1f: Pull complete 
a56cb5ef0726: Pull complete 
9f6cdaad79e0: Pull complete 
c334f9b4fc69: Pull complete 
af093b0c7604: Pull complete 
Digest: sha256:f5ce336d14b0e2c1ad0100be24e9fdb488d727457d3f622efa739ff5a45d899f
Status: Downloaded newer image for oreandawe/storjshare-cli:armv6l
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
e96a798d9e30b22a6120762dc39dc6a049719707c3e00619094490e889b98832
`

**Comment by silveringking** [comment]
I'm formatting the sd card between tries to provide a clean evironment for each build in order to isolate the questions. Anyway, there seems to have issues with your build and raspbian.

**Comment by silveringking** [comment]
Just to show you everything is upgraded:

`pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease               
A ler as listas de pacotes... Pronto                                           
pi@raspberrypi:~ $ sudo apt-get upgrade
A ler as listas de pacotes... Pronto
A construir árvore de dependências       
A ler a informação de estado... Pronto
A calcular a actualização... Pronto
0 pacotes actualizados, 0 pacotes novos instalados, 0 a remover e 0 não actualizados.
pi@raspberrypi:~ $ sudo apt-get dist-upgrade
A ler as listas de pacotes... Pronto
A construir árvore de dependências       
A ler a informação de estado... Pronto
A calcular a actualização... Pronto
0 pacotes actualizados, 0 pacotes novos instalados, 0 a remover e 0 não actualizados.
pi@raspberrypi:~ $ sudo rpi-update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Your firmware is already up to date
pi@raspberrypi:~ $ 
`

**Comment by zannen** [comment]
Please download and run the `check-config.sh` script from the `moby` project: https://github.com/moby/moby/blob/master/contrib/check-config.sh

**Comment by silveringking** [comment]
Doesn't work
`pi@raspberrypi:~/storj $ sudo chmod +x check-config.sh
pi@raspberrypi:~/storj $ ./check-config.sh
./check-config.sh: line 7: syntax error near unexpected token `newline'
./check-config.sh: line 7: `<!DOCTYPE html>'
pi@raspberrypi:~/storj $ 
`

**Comment by silveringking** [comment]
Should I refer raspbian uses armhf images not armv6l images?

**Comment by zannen** [comment]
You have downloaded the webpage, not the script. To get the script directly, use this command:
```bash
wget https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh
```

**Comment by silveringking** [comment]
Prolly I downloaded the page by mistake but I've used wget

I will put here all my command line for this session

`pi@raspberrypi:~/storj $ sudo wget https://github.com/moby/moby/blob/master/contrib/check-config.sh
--2019-03-13 21:02:46--  https://github.com/moby/moby/blob/master/contrib/check-config.sh
A resolver github.com (github.com)...192.30.253.113, 192.30.253.112
A conectar github.com (github.com)|192.30.253.113|:443... conectado.
Pedido HTTP enviado, a aguardar resposta...200 OK
Tamanho: não especificado [text/html]
Saving to: ‘check-config.sh’

check-config.sh                                              [  <=>                                                                                                                            ] 178,03K   448KB/s    in 0,4s    

2019-03-13 21:02:48 (448 KB/s) - ‘check-config.sh’ saved [182301]

pi@raspberrypi:~/storj $ sudo docker run --detach --name mystorjdaemon --restart=always -v /media/pi/storj1:/storj1 -v /media/pi/storj2:/storj2 -v /media/pi/storj3:/storj3 -v /media/pi/storj4:/storj4 -p 4000-4003:4000-4003 -e WALLET_ADDRESS=[edited] -e DAEMONADDRESS=127.0.0.1 -e DATADIR=/storj -e SHARE_SIZE=4.5TB -e RPCADDRESS=0.0.0.0 -e RPCPORT=4000 -e TUNNELING_REQUIRED=TRUE -e STORJ_MONITOR_API_KEY=[edited] -e USE_HOSTNAME_SUFFIX=FALSE oreandawe/storjshare-cli:armv6l
Unable to find image 'oreandawe/storjshare-cli:armv6l' locally
armv6l: Pulling from oreandawe/storjshare-cli
309a8f4417bb: Pull complete 
05b1ad9d506a: Pull complete 
d6e2d725b39d: Pull complete 
57f9f131e2a3: Pull complete 
c44f1c7e2eed: Pull complete 
1d65ff8b0ec2: Pull complete 
9c756ccd8c1f: Pull complete 
a56cb5ef0726: Pull complete 
9f6cdaad79e0: Pull complete 
c334f9b4fc69: Pull complete 
af093b0c7604: Pull complete 
Digest: sha256:f5ce336d14b0e2c1ad0100be24e9fdb488d727457d3f622efa739ff5a45d899f
Status: Downloaded newer image for oreandawe/storjshare-cli:armv6l
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
71862bcf6bfb2c6d0b47aa0ffee96eac9f4259ea570ade23be42cb2ff186a361
pi@raspberrypi:~/storj $ ./check-config.shbash: ./check-config.sh: Permission denied
pi@raspberrypi:~/storj $ sudo ./check-config.sh
sudo: ./check-config.sh: command not found
pi@raspberrypi:~/storj $ cd ..
pi@raspberrypi:~ $ chmod +x /storj
chmod: impossível aceder a '/storj': No such file or directory
pi@raspberrypi:~ $ sudo chmod +x /storj
chmod: impossível aceder a '/storj': No such file or directory
pi@raspberrypi:~ $ sudo chmod +x /storj/check-config.sh
chmod: impossível aceder a '/storj/check-config.sh': No such file or directory
pi@raspberrypi:~ $ chmod +x /storj^C
pi@raspberrypi:~ $ cd storj
pi@raspberrypi:~/storj $ chmod +x check-config.sh
chmod: a alterar as permissões de 'check-config.sh': Operation not permitted
pi@raspberrypi:~/storj $ sudo chmod +x check-config.sh
pi@raspberrypi:~/storj $ ./check-config.sh
./check-config.sh: line 7: syntax error near unexpected token `newline'
./check-config.sh: line 7: `<!DOCTYPE html>'
pi@raspberrypi:~/storj $ ^C
pi@raspberrypi:~/storj $ sudo ./check-config.sh
./check-config.sh: 8: ./check-config.sh: Syntax error: newline unexpected
pi@raspberrypi:~/storj $ ^C
pi@raspberrypi:~/storj $ sudo su
root@raspberrypi:/home/pi/storj# ^C
root@raspberrypi:/home/pi/storj# /check-config.sh
bash: /check-config.sh: No such file or directory
root@raspberrypi:/home/pi/storj# ./check-config.sh
./check-config.sh: line 7: syntax error near unexpected token `newline'
./check-config.sh: line 7: `<!DOCTYPE html>'
root@raspberrypi:/home/pi/storj# exit
exit
pi@raspberrypi:~/storj $ wget https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh
--2019-03-13 21:53:24--  https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh
A resolver raw.githubusercontent.com (raw.githubusercontent.com)...151.101.132.133
A conectar raw.githubusercontent.com (raw.githubusercontent.com)|151.101.132.133|:443... conectado.
Pedido HTTP enviado, a aguardar resposta...200 OK
Tamanho: 10314 (10K) [text/plain]
check-config.sh.1: Permission denied

Cannot write to ‘check-config.sh.1’ (Permission denied).
pi@raspberrypi:~/storj $ sudo wget https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh
--2019-03-13 21:53:35--  https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh
A resolver raw.githubusercontent.com (raw.githubusercontent.com)...151.101.132.133
A conectar raw.githubusercontent.com (raw.githubusercontent.com)|151.101.132.133|:443... conectado.
Pedido HTTP enviado, a aguardar resposta...200 OK
Tamanho: 10314 (10K) [text/plain]
Saving to: ‘check-config.sh.1’

check-config.sh.1                                        100%[================================================================================================================================>]  10,07K  --.-KB/s    in 0,001s  

2019-03-13 21:53:35 (8,67 MB/s) - ‘check-config.sh.1’ saved [10314/10314]

pi@raspberrypi:~/storj $ sudo chmod +x check-config.sh.1
pi@raspberrypi:~/storj $ ./check-config.sh.1
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
error: cannot find kernel config
  try running this script again, specifying the kernel config:
    CONFIG=/path/to/kernel/.config ./check-config.sh.1 or ./check-config.sh.1 /path/to/kernel/.config
pi@raspberrypi:~/storj $ ^C
pi@raspberrypi:~/storj $ sudo ./check-config.sh.1
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
error: cannot find kernel config
  try running this script again, specifying the kernel config:
    CONFIG=/path/to/kernel/.config ./check-config.sh.1 or ./check-config.sh.1 /path/to/kernel/.config
pi@raspberrypi:~/storj $ CONFIG=/path/to/kernel/.config ./check-config.sh.1 or ./check-config.sh.1 /path/to/kernel/.config
warning: or does not exist, searching other paths for kernel config ...
error: cannot find kernel config
  try running this script again, specifying the kernel config:
    CONFIG=/path/to/kernel/.config ./check-config.sh.1 or ./check-config.sh.1 /path/to/kernel/.config
pi@raspberrypi:~/storj $ 
pi@raspberrypi:~/storj $ ^C
pi@raspberrypi:~/storj $ ^C
pi@raspberrypi:~/storj $ 
`

**Comment by zannen** [comment]
Please use three backticks in a row when pasting your console session:

    ```
    like this
    ```

**Comment by zannen** [comment]
Please run the command:
```bash
sudo modprobe configs
```
then try running the `check-config.sh` script again.

**Comment by silveringking** [comment]
```
pi@raspberrypi:~/storj $ sudo modprobe configs
pi@raspberrypi:~/storj $ sudo ./check-config.sh.1
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled (as module)
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled (as module)
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled (as module)
  - "ipvlan":
    - CONFIG_IPVLAN: enabled (as module)
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_FTP: enabled (as module)
    - CONFIG_NF_NAT_TFTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_TFTP: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
``

**Comment by silveringking** [comment]
This is a default install of raspbian made with Noobs (I'm lazy). The only additions were the update of firmware, the upgrade of default packages and the addition of docker and docker.io packages.

**Comment by zannen** [comment]
Your output matches mine, I have the same things enabled and the same things missing.

**Comment by silveringking** [comment]
Ok let me run the installation again.

**Comment by zannen** [comment]
I now notice that you are using `--detach` to run the container in the background. You also received an image ID, indicating that the container started.

To see all containers, running and stopped, please run:
```
sudo docker ps -a
```

You can check the logs of a container with:
```
sudo docker logs name_of_your_container 2>&1 |less
```

**Comment by zannen** [comment]
I don't think you need to run the installation again.

You might need to change some settings and reboot, but don't worry about re-installing.

**Comment by silveringking** [comment]
Could you help me troubleshooting this then?

```
pi@raspberrypi:~/storj $ sudo docker stop 71862bcf6bfb
71862bcf6bfb
pi@raspberrypi:~/storj $ sudo docker rm 71862bcf6bfb
71862bcf6bfb
pi@raspberrypi:~/storj $ sudo docker rmi oreandawe/storjshare-cli:armv6l
Untagged: oreandawe/storjshare-cli:armv6l
Deleted: af093b0c7604d67f399a40a6f797c0f29116774c231440ef9ebff2d5c155868a
Deleted: c334f9b4fc69496cab8437958ae3d4efa92597e4db045c879031e601684e3222
Deleted: 9f6cdaad79e0b978421a3d5ab5e43b30766c4fa490c054dec3913bd6a8fe5876
Deleted: a56cb5ef07261deaafdd6e0e7dd7e4cf6516de174797ad99941cb24e755918e0
Deleted: 9c756ccd8c1f154815b82c6556c183b1a7f9f8a0939b410c1bba8ce332c11893
Deleted: 1d65ff8b0ec26dcbc70808ce839981b9bde13299abb7fc26ab9a6e8b32018407
Deleted: c44f1c7e2eed2ef8a5eff2d07925c9f57d1f01e5a714a189f5cfcaca18f8a3a3
Deleted: 57f9f131e2a309ae18a20da22513a5215d151014bdf3bbc359835d8d23a11340
Deleted: d6e2d725b39d89a79f51a943045aa69958c625b0e016203c53da22e35282e367
Deleted: 05b1ad9d506aeab7affd46baca6eea05657e3d507f884e3d0efed752a113f114
Deleted: 309a8f4417bb2aba7dd04bda4b1ef48df31c49fb4ed82008ad8d3b0f477a166c
pi@raspberrypi:~/storj $ sudo docker run --detach --name mystorjdaemon --restart=always -v /media/pi/storj1:/storj1 -v /media/pi/storj2:/storj2 -v /media/pi/storj3:/storj3 -v /media/pi/storj4:/storj4 -p 4000-4003:4000-4003 -e WALLET_ADDRESS=[edit] -e DAEMONADDRESS=127.0.0.1 -e DATADIR=/storj -e SHARE_SIZE=4.5TB -e RPCADDRESS=0.0.0.0 -e RPCPORT=4000 -e TUNNELING_REQUIRED=TRUE -e STORJ_MONITOR_API_KEY=[edit] -e USE_HOSTNAME_SUFFIX=FALSE oreandawe/storjshare-cli:armv6l
Unable to find image 'oreandawe/storjshare-cli:armv6l' locally
armv6l: Pulling from oreandawe/storjshare-cli
309a8f4417bb: Pull complete 
05b1ad9d506a: Pull complete 
d6e2d725b39d: Pull complete 
57f9f131e2a3: Pull complete 
c44f1c7e2eed: Pull complete 
1d65ff8b0ec2: Pull complete 
90bdcd1b10f9: Pull complete 
61fbaec2ec87: Pull complete 
4ebe6676ab2c: Pull complete 
c7a35aa57a99: Pull complete 
6c4d8d0e93c8: Pull complete 
4ca7289b0d4b: Pull complete 
Digest: sha256:3386b011e1e440bd90bc6dbe312977b9afd9b897a1770e8f55a84fc0ad26723c
Status: Downloaded newer image for oreandawe/storjshare-cli:armv6l
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
9b80f478c3ede2cdc519d9709179b1b78779002af54cb14852f7b0d52d816feb
pi@raspberrypi:~/storj $ 
```

**Comment by silveringking** [comment]
```
pi@raspberrypi:~ $ sudo docker ps -a
CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS                         PORTS                              NAMES
9b80f478c3ed        oreandawe/storjshare-cli:armv6l   "/entrypoint"       27 minutes ago      Restarting (1) 8 minutes ago   0.0.0.0:4000-4003->4000-4003/tcp   mystorjdaemon
pi@raspberrypi:~ $ 
```

**Comment by zannen** [comment]
Please now run the `logs` command:
```bash
sudo docker logs 9b80f478c3ed 2>&1 | less
```

**Comment by silveringking** [comment]
```
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
sed: /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js: No such file or directory
``` 

This all I managed to save.

**Comment by zannen** [comment]
Thanks, that's a nice informative error message :-).

Later today, I'll update `Dockerfile.armv6l` and upload another image.

**Comment by silveringking** [comment]
Thank you, when I update my Pi I will let you know.

**Comment by zannen** [comment]
@silveringking I have updated the container, and tried it like this:
```bash
pi@piTWO:~ $ docker run --rm -ti \
    --name mystorjdaemon 
    -v /home/pi/storjdata:/storj \
    -p 4000-4003:4000-4003 \
    -e WALLET_ADDRESS=0x[ERC20_token_addr] \
    -e SHARE_SIZE=1GB \
    oreandawe/storjshare-cli:armv6l
```

And it has showed this output so far:
```
created directory: '/storj/share'
created directory: '/storj/log'
  * starting daemon in foreground
  * configuration written to /storj/config.json
{"level":"info","message":"attempting to start node with config at path /storj/config.json","timestamp":"2019-03-15T21:39:33.149Z"}
  * starting node with config at /storj/config.json
```

**Comment by silveringking** [comment]
```
pi@raspberrypi:~ $ sudo docker run --detach \
> --name mystorjdaemon \
> --restart=always \
> -v /media/pi/storj1:/storj1 \
> -v /media/pi/storj2:/storj2 \
> -v /media/pi/storj3:/storj3 \
> -v /media/pi/storj4:/storj4 \
> -p 4000-4003:4000-4003 \
> -e WALLET_ADDRESS=[EDITED] \
> -e DAEMONADDRESS=127.0.0.1 \
> -e DATADIR=/storj \
> -e SHARE_SIZE=4.5TB \
> -e RPCADDRESS=0.0.0.0 \
> -e RPCPORT=4000 \
> -e TUNNELING_REQUIRED=TRUE \
> -e STORJ_MONITOR_API_KEY=[EDITED] \
> -e USE_HOSTNAME_SUFFIX=FALSE \
> oreandawe/storjshare-cli:armv6l
Unable to find image 'oreandawe/storjshare-cli:armv6l' locally
armv6l: Pulling from oreandawe/storjshare-cli

309a8f4417bb: Pull complete 
05b1ad9d506a: Pull complete 
d6e2d725b39d: Pull complete 
57f9f131e2a3: Pull complete 
c44f1c7e2eed: Pull complete 
1d65ff8b0ec2: Pull complete 
90bdcd1b10f9: Pull complete 
61fbaec2ec87: Pull complete 
4ebe6676ab2c: Pull complete 
c7a35aa57a99: Pull complete 
6c4d8d0e93c8: Pull complete 
7be4fbe7b18c: Pull complete 
c2b72bd594b2: Pull complete 
Digest: sha256:0d367e5b097fd520a8c6ca6151e4a1f020ed816beb2691261424cf276ed61de7
Status: Downloaded newer image for oreandawe/storjshare-cli:armv6l
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
d90a871438d5f66cd01289275ab1cb37b784b7eb50cb546f2fc7a9f65f32db01
pi@raspberrypi:~ $ 
```

**Comment by zannen** [comment]
As before, you now have a running container. To find out more details, please now view the docker logs for your container:

```bash
sudo docker logs d90a8714 2>&1 | less
```

**Comment by silveringking** [comment]
I didn't use the same container, but I've done the same process this time the error is the following:

```
created directory: '/storj/'
created directory: '/storj/share'
created directory: '/storj/log'

  * starting daemon in foreground


  * configuration written to /storj/config.json
{"level":"info","message":"attempting to start node with config at path /storj/config.json","timestamp":"2019-03-16T17:00:44.946Z"}

  * starting node with config at /storj/config.json
{"level":"info","message":"got status query","timestamp":"2019-03-16T17:00:45.989Z"}
[17:00:46] bda97c302694cf9beb8543889b1f91f2a1ca0f41 | Submit to Storjstat
[17:00:46] ERROR {"error":"Invalid farmer data (spaceUsedBytes)"}
```

**Comment by zannen** [comment]
Ok, we've solved the `exec format error`, and we've determined that `Your kernel does not support memory swappiness capabilities` is just a warning.

Now, for your current error, please investigate yourself, or contact the StorJ team directly.
