### ISSUE TITLE
startup script needed to run daemon

### ISSUE THREAD

**Issue by kim0** [zannen/docker-storjshare-cli#2]
Hi thanks for the good work. I think the Docker command needs to be a shell script that does something like
```
storjshare daemon
storjshare start --config /root/.config/storjshare/configs/*
# then hopefully something like
storjshare logs #-i magic here
```

If the above is not really needed, I guess I'd be using it wrong. Can you let me know how to run it correctly. Storj seems to need "daemon" running beforehand. Thanks!

**Comment by zannen** [comment]
I haven't used storjshare for a while, so the container is a bit out of date. Have you figured out how to run it since commenting?

**Comment by davidak** [comment]
I use it like this:

```
# Create Config.
docker run --rm -ti -v "/var/lib/storjshare/disk1:/var/lib/storjshare" oreandawe/storjshare-cli create --storj 0x###### --size 930GB --storage /var/lib/storjshare/storage --rpcaddress storj1.dyndns.org --rpcport 4000 --maxtunnels 3 --tunnelportmin 4001 --manualforwarding true --noedit --logdir /var/lib/storjshare/log -o /var/lib/storjshare/storjshare.cfg

# Run node
docker run --rm -d -p 4000-4003:4000-4003 -v "/var/lib/storjshare/disk1:/var/lib/storjshare" oreandawe/storjshare-cli start -c /var/lib/storjshare/storjshare.cfg -d
```

Not sure why i would need the daemon...

A better documentation of the usage would be helpful.

**Comment by djchen** [comment]
Running a detached instance, how do you check on the status of it? (ie storjshare status ..)

**Comment by davidak** [comment]
@djchen that is a good question for that i have no answer :D

**Comment by Craftplorer** [comment]
I can recommend the offical wiki about settings storj up on a Synology nas (synology uses dockers). 
https://docs.storj.io/docs/storj-share-daemon-on-synology

**Comment by zannen** [comment]
@Craftplorer I've updated the README with info from the above URL.

@djchen I'll look into it...

**Comment by zannen** [comment]
Running the command:
```bash
docker exec mystorjdaemon storjshare status
```

results in:
```
┌─────────────────────────────────────────────┬─────────┬──────────┬──────────┬─────────┬───────────────┬─────────┬──────────┬───────────┬──────────────┐
│ Share                                       │ Status  │ Uptime   │ Restarts │ Peers   │ Allocs        │ Delta   │ Port     │ Shared    │ Bridges      │
└─────────────────────────────────────────────┴─────────┴──────────┴──────────┴─────────┴───────────────┴─────────┴──────────┴───────────┴──────────────┘
```

**Comment by zannen** [comment]
See also, pull request #4, for nicer startup/entrypoint script.

**Comment by davidak** [comment]
The daemon alone is not useful. You need the shares to mine.

I used it now like this:

```
docker run --detach --name storj --restart=always -v /var/lib/storjshare:/storj -p 4000-4007:4000-4007 oreandawe/storjshare-cli:latest
docker exec storj storjshare start --config /storj/disk1/config.json
docker exec storj storjshare start --config /storj/disk2/config.json
docker exec storj storjshare status
```

This way i have 2 shares (mining on 2 different physical disks) and 1 daemon running.

```
[root@nas:~]# docker exec storj storjshare status

┌─────────────────────────────────────────────┬─────────┬──────────┬──────────┬─────────┬───────────────┬─────────┬──────────┬───────────┬──────────────┐
│ Share                                       │ Status  │ Uptime   │ Restarts │ Peers   │ Allocs        │ Delta   │ Port     │ Shared    │ Bridges      │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ fe02ec50e183ed1f90288e5e9c3266d70549d21a    │ running │ 4m 5s    │ 0        │ 127     │ 3             │ 23ms    │ 4000     │ 119.84GB  │ connected    │
│   → /storj/disk1/data                       │         │          │          │         │ 2 received    │         │ (TCP)    │ (13%)     │              │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ 6c6101af3bbbe3a19d5536422a509dc0d08f637b    │ running │ 8m 43s   │ 0        │ 154     │ 0             │ 34ms    │ 4004     │ 283.61GB  │ connected    │
│   → /storj/disk2/data                       │         │          │          │         │ 0 received    │         │ (TCP)    │ (30%)     │              │
└─────────────────────────────────────────────┴─────────┴──────────┴──────────┴─────────┴───────────────┴─────────┴──────────┴───────────┴──────────────┘

```
I think when the container restarts, i'm not mining anymore, what is bad. The PR #4 has a better approach with the entrypoint script.

**Comment by zannen** [comment]
I've merged #4, closing this issue.

**Comment by Zxxxx** [comment]
┌─────────────────────────────────────────────┬─────────┬──────────┬──────────┬─────────┬───────────────┬─────────┬──────────┬───────────┬──────────────┐
│ Share                                       │ Status  │ Uptime   │ Restarts │ Peers   │ Allocs        │ Delta   │ Port     │ Shared    │ Bridges      │
├─────────────────────────────────────────────┼─────────┼──────────┼──────────┼─────────┼───────────────┼─────────┼──────────┼───────────┼──────────────┤
│ abcabcabcabcabcabcabcabcabcabcabcabcabca    │ running │ 19h 7m … │ 0        │ 1       │ 0             │ 0ms     │ 4000     │ ...       │ connected    │
│   → /storj/share                            │         │          │          │         │ 0 received    │         │ (uPnP)   │ (...%)    │              │
└─────────────────────────────────────────────┴─────────┴──────────┴──────────┴─────────┴───────────────┴─────────┴──────────┴───────────┴──────────────┘


Is this correct？

**Comment by davidak** [comment]
@Zxxxx you have not much peers. have you configured port forwarding?

https://docs.storj.io/v1.0/docs/storjshare-troubleshooting-guide#section-port-forwarding
