### ISSUE TITLE
RPC Daemon should listen to 0.0.0.0

### ISSUE THREAD

**Issue by sdesbure** [zannen/docker-storjshare-cli#5]
# Why
As storjshare runs inside its own docker, it's impossible to gather stats (for [strojdash](https://www.storjdash.com/), [Storjstat](https://storjstat.com/), [StorjBoard](https://storjboard.pro/), [Storj Telegraf plugin](https://github.com/salgieri/StorJ-Telegraf-Plugin/blob/master/storjstats.js), [Stroj Collectd Plugin](https://github.com/bobey/storj-collectd-plugin), ...) without rebuilding a container with CLI + the one who'll gather stat.

If the RPC daemon listen to 0.0.0.0, any other docker with a link to this docker would be able to access it.

It would then be a more "docker-way" of doing.

# How

Because of Storj/storjshare-daemon#294, it's complicated for now to "just" make a volume on the `daemon.json` inside `/root/.config/storjshare/configs/`.

So an ugly way would be to replace the default config which is in `/usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js`

For example by adding a switch in Entrypoint:

```bash
if [ -n $ "${DAEMON_LISTEN_ALL}" ]; then
  sed -i 's/127\.0\.0\.1/0.0.0.0/' /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js
fi
```

If I'm not the only one interested in such feature, I can make a pull request (especially if someone has a brilliant idea about the switch naming ^_^.

**Comment by zannen** [comment]
Thanks, @sdesbure.
