### ISSUE TITLE
Docker "no such file or directory" error from standard_init_linux.go:185

### ISSUE THREAD

**Issue by Dids** [zannen/docker-storjshare-cli#8]
I'm currently trying to get this running on an Unraid installation (regular x86 hardware and proper Docker support), and while all my other Docker containers run just fine, this one, however, does not:

```
standard_init_linux.go:185: exec user process caused "no such file or directory"
```

Apparently the error above is coming from Docker, and is most often related to some of the internal image files using Windows line endings: https://stackoverflow.com/a/47143665/1856821

Anyone else seeing this, or am I the only one?

**Comment by zannen** [comment]
What command are you using to run the `storjshare-cli` container? Please also share log snippets if you have them.

The `entrypoint` and `versions` scripts both have Unix line endings (`\n`) not Windows (`\r\n`), as verified by the Linux `file` command.

You can see different sample output from `file`:
```bash
bash$ echo -ne 'Windows\r\nzzz\r\n' | file -
/dev/stdin: ASCII text, with CRLF line terminators
bash$ echo -ne 'Unix\nzzz\n' | file -
/dev/stdin: ASCII text
```

**Comment by Dids** [comment]
Unraid uses the following command to start the container:

```sh
docker run -d --name=StorjShare --net=bridge -e WALLET_ADDRESS=<WALLET_ADDRESS> -e SHARE_SIZE=50GB -e STORJ_MONITOR_API_KEY=<API_KEY> -p 4000-4003:4000-4003/tcp -v /mnt/user/Docker/StorjShare:/storj:rw oreandawe/storjshare-cli:latest
```

Unfortunately the log files have zero extra information, so I'm not sure how to debug this further.

**Comment by Dids** [comment]
Just to update on this, I tried setting `--entrypoint /versions` to see if the entrypoint itself is having issues, but still getting the same error, so that's likely not related.

**Comment by PhilipSchmid** [comment]
@Dids The Docker environment variable `DATADIR`  is **required** (e.g. `-e DATADIR=/storj`) since it's used inside the `entrypoint` script.

Regards,
Philip

**Comment by PhilipSchmid** [comment]
@Dids Hmm.. Yup, sorry, your are right. I just looked at the `entrypoint` script and didn't notice the default value of the `DATADIR` environment variable inside the `Dockerfile`. My Docker Image [pschmid/docker-storjshare-cli](https://hub.docker.com/r/pschmid/docker-storjshare-cli/) still works, so I guess the breaking change comes from the commit [99a8280d14b068ae0c0f8551c10935101d0c123f](https://github.com/zannen/docker-storjshare-cli/commit/99a8280d14b068ae0c0f8551c10935101d0c123f). This is just my current guess - I will now have a more detailed look into the issue.

I'll keep you updated.

Regards,
Philip

**Comment by PhilipSchmid** [comment]
@Dids Found and fixed the issue. As long as the PR https://github.com/zannen/docker-storjshare-cli/pull/9 is not merged by @zannen, you can use the Docker image `pschmid/docker-storjshare-cli:testing` which currently includes the fix.

Any feedback is welcome. Thanks.

Regards,
Philip
